// Code generated by Microsoft (R) TypeSpec Code Generator.

package todo;

import io.clientcore.core.annotation.Metadata;
import io.clientcore.core.annotation.TypeConditions;

/**
 * The FileAttachmentMultipartRequest model.
 */
@Metadata(conditions = { TypeConditions.IMMUTABLE })
public final class FileAttachmentMultipartRequest {
    /*
     * The contents property.
     */
    @Metadata(generated = true)
    private final TodoFileAttachment contents;

    /**
     * Creates an instance of FileAttachmentMultipartRequest class.
     * 
     * @param contents the contents value to set.
     */
    @Metadata(generated = true)
    public FileAttachmentMultipartRequest(TodoFileAttachment contents) {
        this.contents = contents;
    }

    /**
     * Get the contents property: The contents property.
     * 
     * @return the contents value.
     */
    @Metadata(generated = true)
    public TodoFileAttachment getContents() {
        return this.contents;
    }
}
